### ISSUE TITLE
[희진님] BOJ-11725, 1991 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/algorithm-strategies#17]
### [트리의 부모 찾기](https://github.com/psychology50/algorithm-strategies/blob/main/heejin/boj-11725/main.swift)
- 인접 행렬 문제에만 익숙해지면, 인접 리스트가 나왔을 때 당황하게 될 것 같아 내드린 문제입니다.
- 사실 트리를 만들어야 하는 문제일 거라 생각하고 드린 건데, 엉뚱한 걸 드렸네요. 
- 그래도 깔끔하게 풀이하셔서 잘하셨어요.

### [트리 순회](https://github.com/psychology50/algorithm-strategies/blob/main/heejin/boj-1991/main.swift)
- 에고, 스위프트에서 문자열 다루는 게 왜이렇게 극성인지 모르겠네요. 문자를 아스키 코드로 변환하는 방식은 굉장히 자주 쓰이니 이참에 확실히 숙지해두시는 게 좋을 듯 합니다.
- 함수 배열을 만들어서 `forEach`를 하는 방식이 독특하네요. 언어 특성을 잘 활용하셨어요.
- 눈치 채셨겠지만, 이 문제도 인접 리스트 문제에 익숙해지길 바라는 마음에서 드렸습니다.
- 솔직히 전위/중위/후위 순회 문제가 코테에서 나오는 경우는 잘 없지만, 오랜만에 환기시켜드릴 겸 드린 건데 잘 해결하셨어요

**Comment by heejinnn** [comment]
트리 문제 푸니까 옛날에 자료구조 듣던 때가 생각나며 좋았습니다 허허 감사합니다~~
