### ISSUE TITLE
커밋 수정 질문

### ISSUE THREAD

**Issue by SubiHwang** [psychology50/algorithm-strategies#18]
11170번 초기 커밋 메시지를 subi/boj-1224에다가 해버렸네요!
이럴 때는 1224 커밋을 이전으로 돌리고 11170번 코드를 초기 코드로 바꾸고 다시 커밋한 다음, 완성된 코드로 또 바꿔서 커밋해줘야 하는 걸까요?

**Comment by psychology50** [comment]
커밋 메시지만 잘못 쓰신 거라면, 굳이 그렇게까지 하실 필욘 없습니다

**Comment by SubiHwang** [comment]
네!
