### ISSUE TITLE
[희진님] BOJ-5212, 1629 코드 리뷰

### ISSUE THREAD

**Issue by psychology50** [psychology50/algorithm-strategies#19]
### [지구 온난화](https://steelbeartaeng2.tistory.com/44)
- 저랑 굉장히 유사하게 풀이하셨네요. 오히려 저보다 더 군더더기 없는 로직이었던 것 같습니다.
- 특히 배열을 순회하면서 바로 min, max 좌표를 구한 것과 바다에 잠긴 섬을 `.`이 아니라 `*`로 구분함으로써 이후 전처리 과정을 완전히 생략하셨네요. 제가 보고 배웠습니다.
- 이건 단순히 제 생각이기에 참고만 해보시면 좋을 것 같습니다.
   - 파이썬도 스위프트처럼 함수를 하나도 작성하지 않고, 모든 코드를 전역에 작성할 수 있지만 전 그렇게 안 했었습니다.
   - 함수 호출 횟수가 그리 크지 않다면, 함수 호출로 생기는 오버헤드는 무시할만한 수준이고 오히려 코드를 이해하는데 도움을 주니까요.
   - 희진님의 코드는 총 3 부분으로 구분할 수 있다고 봅니다. 이 부분들을 함수로 처리했을 때의 이점은 로직이 실패하더라도 디버깅을 할 때 정말 유용해져요. (a라는 함수에 input을 넣었을 때, output이 나오지 않는다면 "a의 로직에 문제가 있다"라는 게 명확해집니다.)
   - 또한 전역 변수에 코드를 늘어놓았을 때 발생할 수 있는 문제점들을 많이 방지할 수도 있구요.
   - 오해하실까 봐 다시 한 번 말씀드리지만, 제 생각을 말씀드린 것 뿐이니 희진님께서 이런 케이스도 고려해보신 후에 편한 방식을 고수하시길 바랍니다.

### [곱셈](https://steelbeartaeng2.tistory.com/45)
- 제출하신 걸 봤는데 맞은 다음에 런타임 에러가 나셨더라구요. 포스팅을 위해 테스트 해보신 건가요?
- `divide`를 홀수일 때와 짝수일 때를 나누어서 호출하고 계신데, 아마 필요 없을 겁니다.
   - `3/2` 와 `2/2`의 결과를 int로 받으면 둘의 결과는 다를까요?
   - 아마 코드를 다음과 같이 줄일 수도 있었을 겁니다.
      ```swift
         let d = divide(N/2)
         return (N % 2 == 0) ? d % C * d % C  : d % C * d % C * A % C
      ```
   - 이 문제를 내드린 건 모듈로 연산이 이렇게도 쓰일 수 있다는 걸 보여드리고 싶었습니다. 보통 연산 결과를 어떤 값의 나머지로 구하라는 조건을 많이 주기 때문에, 혹시나 이게 왜 되지 싶었다면 이번 기회에 짚고 넘어가세요.

**Comment by heejinnn** [comment]
지구온난화: 네헵 전역변수에 대해 고려해볼게요!
곱셈: 넵 블로그에 올리기 전에 이렇게 코드를 짜면 런타임에러가 난다는 것을 확인하고 싶어서 코드 올려봤어요! 
아,,, 홀수와 짝수 나눌 필요가 없었네요 허허 확인했습니다!
